version: '3.4'


networks:
  backend:

services:
  
  fullstackdb:
    container_name: fullstack-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 18002:1433 
    environment:
       - ACCEPT_EULA=Y
       - MSSQL_SA_PASSWORD=Password1@123
    networks:
       - backend

  fullstack.api:
    container_name: fullstack-api
    image: ${DOCKER_REGISTRY-}fullstackapi
    build:
      context: .
      dockerfile: FullStack.API/Dockerfile
    networks:
       - backend
    ports:
      - 18005:85

    environment:
      - DB_HOST=fullstackdb
      - DB_NAME=fullstackdbMain
      - DB_MSSQL_SA_PASSWORD=Password1@123
